language: java

jdk:
- oraclejdk8

sudo: required

services:
  - postgresql

addons:
    postgresql: "9.6"

env:
  global:
  - PGPORT=5432

before_script:
- bash install-postgres-10.sh
- psql -c 'create database pumadb;' -U postgres
- psql -c "alter user postgres with password 'puma';" -U postgres -h localhost


deploy:
  provider: heroku
  api-key:
    secure: uLcwsLzh6yOalqen8uD7Mut+W7BdpkYCPi5ZfjnphInbJr2kTUfDvOsX/mqglzBIKG00PU7PqwSVls4RahkUwYtS5IcPGtnwpZHR4qLnm+dRzJKyQY8Vr1lPmfGIDlCgNeHFyXtQj5eMG8hP46bF7L0LW7742DkCO6B6wVydxQo+eiZomfb3FslCwq2oY1ulOsk6eiq0G2aaFa6PVq9doY8bcIr9mSXp0wQO5qFnJdvQjXCH8h5iS3F9vh0c3G5Srly5E6V3k0/28m9ZElX5ogP+sKUb9y+hi1fHHvZbdP0GBDfluVCXYmM+ADMJfgSqbymkBQT/5ibEJo1VNgOTRa/pLtZbRNpE2FvN5mKR/QlEo1HoPupHu+rJlsHxiDElwfrTFLuST2zN3Qjzpg16jXP+hDkgeySzJR8ElQX8P4D9x1UnGrUs/1YEXyGBk3c4hBOT+bOr4gP8ReLDec/7SqC7fPNBJ6Mgo+QErdw5J/Q4naZR3vNCJosiw0lpU7yGa3UUhrmfoNoYJ8qA39dvqNKuJl04GAiBHuG3P5BEriOGLEpP1fO8fKSyBtRNcKWev6brHVorPKl8UxGa9UyKmAHS6ZJJUA7Oij9cvTp7h8z2suopU7yenrqtEU1SEBFgVCNtsHZum/u2xSHaUixNisSo4/Y049JCW5dcagmppPQ=
  app: backend-puma
